### ISSUE TITLE
Index List exceeds page width

### ISSUE THREAD

**Issue by krisko** [searchtechnologies/kibana-logbrowser#3]
Hello,
we have many indices and the list in this plugin exceeds page.
We can use filter, but it would be nice to have a drop down menu with indices list.

thank you

**Comment by elessarkrin** [comment]
We will add it as soon as possible, thanks for the feedback

**Comment by elessarkrin** [comment]
Done in release: https://github.com/searchtechnologies/kibana-logbrowser/releases/tag/1.0.2
